"""Add likes column to Poem model

Revision ID: 6fdffcd1b951
Revises: c60365ca25cc
Create Date: 2025-05-11 21:54:39.465277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdffcd1b951'
down_revision = 'c60365ca25cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poem', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
