"""Initial migration.

Revision ID: c28b923c0f0b
Revises: 6fdffcd1b951
Create Date: 2025-05-14 08:31:42.409122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28b923c0f0b'
down_revision = '6fdffcd1b951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poem', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poem', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
